name: test pull request issues
on: 
    pull_request:
        types: [opened, synchronize, edited]
jobs:
  test-pull-request-issues:
    runs-on: windows-2019
    steps:
      - name: Pull request issues
        if: ${{ !github.event.pull_request.draft }}
        uses: tonyhallett/ReleaseManager/get_pull_request_issue@main
        with:
            useCommitMessages: 'false'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Wait for mergeable
        uses: tonyhallett/ReleaseManager/wait_for_mergeable@main
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        //wtf
      
