name: test yaml
on: 
    pull_request:
        types: [opened, synchronize, edited]
jobs:
  build-and-prerelease-vsix:
    runs-on: windows-2019
    steps:
      - name: Remove release assets
        uses: tonyhallett/ReleaseManager/get_pull_request_issue@main
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Demo errors
        uses: boneskull/more-linked-issues-action@v0.2.1
        with:
            github-token: '${{ secrets.GITHUB_TOKEN }}'
