name: Workflow dispatch
on:
  workflow_run:
    workflows: [Push vsix artifact pull release and comment]
    types: [completed]

jobs:
  workflow-dispatch:
    name: repo dispatch with event and conclusion
    runs-on: windows-2019
    steps:
      - name: repo dispatch
        uses: tonyhallett/workflow-run-conclusion-dispatch-action@v1.1.0
        with:
            GITHUB_PAT: ${{ secrets.PAT }}
            eventNameInEventType: 'true'
      
      

